### ISSUE TITLE
knitr option collaspe is not honoured

### ISSUE THREAD

**Issue by renozao** [rstudio/flexdashboard#102]
When using option `collapse = TRUE` in default html output I get all messages output by a single chunk all in a single `<pre><code>` block, which is the desired behaviour. 
However they appear in separate blocks when using `flex_dashboard` output. See code below.
I am using the CRAN version of the package.
Thanks.

```R
cat(file = 'test-default.r', "#' ---
#' title: 'Messages collapsed'
#' ---

#+ echo = FALSE, collapse = TRUE, message = TRUE
message('a')
message('b')
")

cat(file = 'test-flexboard.r', "#' ---
#' title: 'Messages collapsed'
#' output: flexdashboard::flex_dashboard
#' ---

#+ echo = FALSE, collapse = TRUE, message = TRUE
message('a')
message('b')
")

cat(rmarkdown::render('test-default.r'))
cat(rmarkdown::render('test-flexboard.r'))
```

**Comment by renozao** [comment]
The latest Github version (cae0c06d) also has this problem.

**Comment by sjspielman** [comment]
+1

**Comment by gadenbuie** [comment]
I'm pretty sure this is because flexdashboard is provding a custom `chunk` knit hook:

https://github.com/rstudio/flexdashboard/blob/ddcfd7e2d582a2b01fe6a7812a586da5c219a2c3/R/flex_dashboard.R#L198-L206

Quarto ran into a similar issue and solved it as described here: https://github.com/yihui/knitr/issues/2043
