### ISSUE TITLE
Debug Flexdashboard with Shiny Engine

### ISSUE THREAD

**Issue by maxmoro** [rstudio/flexdashboard#115]
It is very complex to debug Flexdashboard with Shiny engine, adding the **browser()** command doesn't help.
Would be great allowing the code to stop and debug during the Flexdashboard  with Shiny engine

Thanks
Max

**Comment by gadenbuie** [comment]
It sounds like you're wanting to debug a flexdashboard and would like to use `browser()` to debug it interactively. This is possible, if not widely advertised! Instead of running the dashboard via the Run Document button in RStudio, you can use `rmarkdown::run()` to run your app. When executed in this way, your `browser()` statements will drop you into the interactive debugger.

```r
rmarkdown::run("my-dashboard.Rmd")
```
