### ISSUE TITLE
html file having problem on vertical scrolling

### ISSUE THREAD

**Issue by Bryant-zhu** [rstudio/flexdashboard#173]
Hi there 
 I basically made a dashboard using mostly HighcharteR .
 it works all good on web browser on pc.

as I try to transplant this on mobile device, I found it so hard to scroll down on mobile browser.

was this mostly due to the nature of highchart? or nature of flexdashboard ?

**Comment by gadenbuie** [comment]
I'm guessing the issue here is probably either that there wasn't a margin around the plot element that you can use as a touch target to scroll down or that highcharter is using the touch events to change the plot and making it difficult to scroll down. Or probably both.

If you can try to add padding around the plot, that might help you find a place to "grab" the outer document.

I'm going to close this for now, please feel free to open a new issue with a reproducible example if you continue to face this problem!
