### ISSUE TITLE
JS user defined function in navbar link

### ISSUE THREAD

**Issue by Patanouque** [rstudio/flexdashboard#208]
Hello,
I'm trying to build a flexdashboard document with a help link in the navbar that triggers a modal.
For the modal I'm using the package bsplus and it works great if I put a button in the dashboard.
I would like to trigger the opening of the modal with an icon in the navbar, for exemple with a onclick argument but it is not handled by flex_dashboard

![repro_ex_modal_rmd](https://user-images.githubusercontent.com/27449850/50634720-edebd700-0f4f-11e9-8257-bbe3ccbea43a.png)

For that I try to use an javascript function  that would be

`$( "#navbar a" ).click(function() {
     $("#modal_markdown").modal();
  });`

It works great if I run it in the javascript console in google chrome developper tool, after the dashboard is loaded but I can't make it work using `<script>` or `tags$script` inside the dashboard body

Here is what I tried: 
- using <script> or tags$script()
- using include in yaml (in_header, before_body, after_body) in case the JS code has to be executed outside the body
- create a custom `navbar_links` function based on [https://github.com/rstudio/flexdashboard/blob/master/R/flex_dashboard.R](https://github.com/rstudio/flexdashboard/blob/master/R/flex_dashboard.R) that would take a onclick argument, but couldn't get the dashboard to knit ( Error in lapply(.x, .f, ...) :  argument "vars" is missing, with no default )

After a few hours of digging the problem I guess there has to be a much simpler solution

here is a reproducible example:

``````
---
title: "reprod_ex"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    navbar:
      - { icon: "fa-question-circle",  align: right}
---


```{r setup, include=FALSE}
library(shiny)
library(bsplus)
```

```{r}
  bs_modal(
    id = "modal_markdown", 
    title = "Using Markdown",
    body = includeMarkdown(system.file("markdown", "modal.md", package = "bsplus"))
  )
```

### 1st tab

```{r}
bs_button("Click for modal", button_type = "primary") %>% bs_attach_modal("modal_markdown")
```
``````

Thanks a lot for any help you can provide !

**Comment by proctorm** [comment]
I'm also interested in running a user defined function from a click event on a navbar link. 

I have managed to get your example working by introducing a delay of 1000 ms. This seems to work regardless of the way the JS is brought into the document (i.e with `<script>` or `tags$script`). I've just added this js chunk below the setup chunk to get yours to work:
````html
```{js}
setTimeout(function(){
  $( "#navbar a" ).click(function() { $("#modal_markdown").modal(); });
}, 1000);
```
````
I believe the underlying issue is that the HTML elements in the navbar are not yet created at the time the user defined script runs. I am very much a web development novice so this could be completely wrong. However, there is an article on the RStudio website talking about `runtime: shiny` documents (https://shiny.rstudio.com/articles/packaging-javascript.html#r-markdown-only-use-a-js-chunk) that says:

> (One caveat for runtime: shiny apps, regardless of which option you choose: your Rmd is not rendered until well after the browser page has loaded, so you can’t rely on the DOMContentLoaded event, or its jQuery equivalent, $(document).ready().)

This seems to apply to this situation even though `runtime: shiny` is not being used. 

By introducing the delay, I'm guessing this gives the time for the navbar elements to be created. Although this does get it to work, it is a bit of a workaround. I would love to know if anyone is able to address the root of the problem?

**Comment by jjallaire** [comment]
That's correct, they are indeed not yet created when the document loads (they are created dynamically from a data structure within the document).

We actually trigger a custom jquery event when the dashboard layout is complete here: https://github.com/rstudio/flexdashboard/blob/master/inst/rmarkdown/templates/flex_dashboard/resources/flexdashboard.js#L152. 

So something like this:

```javascript
$(document).ready(function() {
  $('#dashboard-container').on('flexdashboard:layoutcomplete', function() { 
    $("#navbar a").click(function() { $("#modal_markdown").modal(); });
  })
))
```

**Comment by proctorm** [comment]
Fantastic! FYI, you have a typo on your last line, should be `})`, otherwise works great :smiley:

**Comment by Patanouque** [comment]
Great ! 
thanks a lot
