### ISSUE TITLE
Several ggplotly blank when dashboard gets big

### ISSUE THREAD

**Issue by Vidaringa** [rstudio/flexdashboard#222]
My flexdashboard is behaving strangely. Several of my ggplotly graphs turn blank when the dashboard gets (too?) big. I tried to make a small reproducible example but it's not easy. I'm working with fairly large dataset (~1.6 gb). The code runs so there is nothing wrong with my code.
When I tried to split the dashboard into two dashboards, everything works. See attached screenshots.

![flexdashboard_vr](https://user-images.githubusercontent.com/20194883/59769299-60016f80-9295-11e9-99f2-bb7a0c6b47eb.PNG)

Dashboard after splitting in two parts.
![flexdashboard_vr_2](https://user-images.githubusercontent.com/20194883/59769303-61cb3300-9295-11e9-9ee0-72c6876bcea8.PNG)

**Comment by nyudanin** [comment]
I'm having the same issue--when I split the dashboard into two dashboards, everything is rendering just fine. Is this some memory limit issue?

**Comment by boraelle** [comment]
I didn't get the meaning of splitting the dashboard into two dashboards that you mentioned, but saving each graphs as RDS file would be work. Save each works and read them again when you show on dashboard.

**Comment by Vidaringa** [comment]
Ok I'll try saving each graph as RDS.  But what I mean by splitting the dashboard is that I took ~50% of the code and put it in new .Rmd file and the rest to a separate .Rmd file, both using the same data source. When I did that, both dashboards works perfectly. But when I try to run is it as one big dashboard, some graphs (always the same graphs) turn blank.

**Comment by Vidaringa** [comment]
@boraelle just a thought, why should it work to save each graph as RDS just to read it in again?

**Comment by cderv** [comment]
What did you split exactly in your code ? You made two differents dahsboard 2 HTML files instead of one ?  
With flexdashboard, everything is in one HTML file so everythings load ate the same time. You may try `self_contained = FALSE` to ease the loading so that everything (ployt.js including) is not put inside a unique html document. 
just an idea: you may get some hints in your browser console log. Plotly is a js library and there are maybe some loading issues in the browser (due to the size of the data ?)

**Comment by cderv** [comment]
> Yes, I made two different dashboards instead of one.

That may be everything in the same html file loading at the same time that is causing issue. You could try one dashboard with self_contained = false. or use another framework like a Rmarkdown website to split in different files that will load separately in the browser. 

If you can get some logs from browser loading, it could help identify what is taking long.

**Comment by jp-myers** [comment]
I was having a very similar issue and it appears to be something with the latest version of the htmlwidgets package (v1.5).  Installing htmlwidgets 1.3 fixed the problem for me.

**Comment by jcheng5** [comment]
@jp-myers Any chance you could provide a reproducible example? That would be a huge help!

**Comment by jp-myers** [comment]
@jcheng5 No problem - I think I have isolated the issue in our dashboard to the dyStackedBarGroup function in the dygraphs package.  So if you run the code at the link below with htmlwidgets 1.3 it should render without issue, while running with 1.5 will result in blanks for charts 2 and 3.

https://gist.github.com/jp-myers/33b6efdca29fa5f102b78ef664828b58

Thank you for all of your contributions to the R community!

**Comment by aadiremmik** [comment]
Similar problem here. Flexdashboard (static html) worked just fine, I added new items and at some point some plots just stopped to be displayed. I have 1 plotly plot, 3 ggplotly plots and 3 DT tables that are not displayed any more. In the rest of the document there are both plotly and ggplotly plots displayed with no problems, but it seems that none of the DT tables are displayed. The problem is the same in both RStudio Viewer and browser (Edge and Chrome).

If I remove the rest of flexdashboard pages from .rmd document, then the problematic plots and DT tables are displayed on hte remaining page without any problems.

**Comment by cpsievert** [comment]
If any of you are still having issues after updating htmlwidgets, flexdashboard, and plotly, please file a new issue with a reproducible example
