### ISSUE TITLE
"source_code: embed" produces error when concatening strings containing html code

### ISSUE THREAD

**Issue by Psqrt** [rstudio/flexdashboard#227]
Hello,

The following code doesn't work when knitting the dashboard:

````
---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    source_code: embed
---



```{r}
img_url = "https://i.creativecommons.org/l/by-sa/4.0/88x31.png"

img_url_html = paste0("<img src='", img_url, "' height='76'></img>", sep = "")
```

`r img_url_html`
````

It produces a pandoc error:
```
File ", img_url, " not found in resource path
Error : pandoc document conversion failed with error 99
```
However, when I remove `source_code: embed`, it works fine. The workaround to keep `source_code: embed` and knit correctly, is to deliberately make a typo in the `paste()` function so it doesn't recognize html code then fix the typo with some string manipulation functions.

**Comment by cderv** [comment]
Hi, 

This is an issue because currently html entities from the code are not escaped when inserted inside 
`<pre class="line-numbers"><code class="language-r">` 
That is why pandoc interprets `<img` as an incomplete image tag. 

As a workaround you can use R code to create html instead of pasting strings
````r
---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    source_code: embed
---



```{r}
img_url = "https://i.creativecommons.org/l/by-sa/4.0/88x31.png"

img_url_html <- htmltools::img(
  src = img_url,
  height = 76
)
```

`r img_url_html`
````

I will propose a PR to fix as it seems easy.
