### ISSUE TITLE
Problem with mobile sizing

### ISSUE THREAD

**Issue by rpmeira** [rstudio/flexdashboard#266]
I have a dashboard with several menus, what should no be a problem in mobile sreens because they should be grouped together. But they are not. 

1) what should appear on mobile screen:

![Sem título](https://user-images.githubusercontent.com/64609486/82346283-a2af5880-99cc-11ea-88b2-d919110e03a9.png)

2) what actually appear:
 
![Sem título2](https://user-images.githubusercontent.com/64609486/82346304-a8a53980-99cc-11ea-9663-aa35f97a3616.png)

How can I fix this issue?

**Comment by cderv** [comment]
hello, 

Running the [multiple page example](https://rmarkdown.rstudio.com/flexdashboard/layouts.html#multiple_pages) and looking into it in browser with the mobile mode activated in developer console (F12) shows the correct behavior. 
It is the same when looking at the flexdashboard website and example on my mobile directly. 

That means I can't reproduce your issue currently.

Hint: Sometimes browser on mobile phone can be switched in desktop mode so that it prints as-if on a computer. You may need to check for that on your mobile browser.

Anyway, in order to look into your specific case and to help you we need more information than screenshot. Can you provide a reproducible example ? or a content you would have published somewhere on the web ? 

Thank you.

**Comment by RafaelPeixotoMeira** [comment]
Hi,

I'm sorry for the lack of information. I've published that dashboard here: https://rpubs.com/Rafael_Peixoto/macro
As you can see, it doesn't work properly on mobile devices.
I don't think the issue is at my mobile broser, as every person I've asked about reported me the same problem.
If you need the sorce code I can post here, jut tell me..

Thank you.

**Comment by RafaelPeixotoMeira** [comment]
Hi,
Sorry if I'm rushing you, but did you manage to look at that dashboard I've published?
I still can't figure out how to make it work properly at mobile sreen. 
Here is the source code, if you want to check it.
[macro_flexdash.txt](https://github.com/rstudio/flexdashboard/files/4682437/macro_flexdash.txt)

Thank you.

**Comment by cderv** [comment]
> As you can see, it doesn't work properly on mobile devices.

Yes once published on Rpubs, it does not render as you expect. I am not sure that there is an issue with your code. It seems possible that this is due to Rpubs website that include you're dashboard.
Other content have the same issue, like https://rpubs.com/Da_As_Kumi/561742 

What is strange is that the mobile preview mode in browser on my computer shows the correct rendering.

One test to be sure it is linked to the plateform Rpubs would be to published your code another way, like as a standalone html file on github page or netlify for example.

I did a quick test try to publish the example for multiple page on RPubs then on netflify (just dropping a folder with the flexdashboard as index.html) and I can confirm the difference. 
* Rpubs : https://rpubs.com/cderv/demo-flexdash- => same rendering issue on mobile
* Netlify: https://kind-stonebraker-ca951e.netlify.app/ => correct rendering

I don't really know what to look for in flexdashboard currently without more insight on Rpubs. 
You can change your host provider to deploy you dashboard another way that render your nav bar correctly. Github page is an easy option if you already have a github repo. Netlify is very quick for a manual deployment by dropping static files as folder with an index.html

Hope it helps

**Comment by RafaelPeixotoM** [comment]
Hi,
thank you for verifying this issue. It's too bad that Rpubs doesn't render my nav bar correctly, since it's a very easy and quick way to publish my dashboards. 

I've tried the alternatives you've refered to, but I couldn't do it. I'm new to Github, so I don't have a repo (I don't even know how to make one). On Netlify, I've tried to drop both my '.rmd' and my '.html' files, but it didn't work. I've made that dashboard interily on a single '.rmd' file, so all I have is this file and the '.htm' file that is generated when I press "knit" in RStudio. 

If you happen to know a more easy way to publish this dashboard, or how I can make it to work on Netlify, that would be great. 
Anyway, thank you a lot for your help.

**Comment by cderv** [comment]
> If you happen to know a more easy way to publish this dashboard, or how I can make it to work on Netlify, that would be great.

Trick is you need to have a folder with your html file named `index.html`, and then drag and drop this folder to netlify. Easiest way is using https://app.netlify.com/drop 

What I have done for https://kind-stonebraker-ca951e.netlify.app/ is just that. 
*  renaming the html file rendered after I press the knit button to `index.html` 
* put in in a folder with the app name. 
* Then I dragged and dropped this folder in Netlify. 

You'll find this very new webinar interesting I think. https://rstudio.com/resources/webinars/sharing-on-short-notice-how-to-get-your-materials-online-with-r-markdown/
Look at the very first (until 10m I think) to have a live demo of this process. 

> https://rstudio.com/resources/webinars/sharing-on-short-notice-how-to-get-your-materials-online-with-r-markdown/

You should post in https://community.rstudio.com to explain the issue and your use case. I think it would be interesting to catch the attention of people managing RPubs. 

@yihui do you know who can help on why flexdashboard on Rpubs does not respond to mobile sizing ?

**Comment by RafaelPeixotoM** [comment]
> You'll find this very new webinar interesting I think.
https://rstudio.com/resources/webinars/sharing-on-short-notice-how-to-get-your-materials-online-with-r-markdown/

This really helpped! I managed to upload correctly this time. The site is up and running now. And, most importantly, its rendering correctly. 

I'll post in  https://community.rstudio.com explaning my case, maybe there's other people going through the same issue. 

Thank you so much for your patience and time! I really apreciate.

**Comment by yihui** [comment]
> @yihui do you know who can help on why flexdashboard on Rpubs does not respond to mobile sizing ?

Sorry, but I don't know the reason. All I know is that Rpubs uses an iframe to show an HTML page built from R Markdown, but that shouldn't affect the responsiveness of dashboards.

**Comment by jcheng5** [comment]
I have a feeling it has to do with the `<meta name="viewport">` which is specified in the flexdashboard:

```
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
```

I'm not sure whether it would make sense to put such a tag on the rpubs frame.

@RafaelPeixotoM As a clumsy workaround, and if you don't mind an ugly URL, you can look at the source of the rpubs page and pick out the iframe URL, in this case https://rstudio-pubs-static.s3.amazonaws.com/602099_a6cb9b4b86224b17a990cb89d595c24a.html. I'm sure that will look right on mobile. You could use a link shortener to give it a shorter URL, though the full URL will still show up in the browser location bar.

**Comment by ndevln** [comment]
Hi,

is there a way to modify the default `<meta name="viewport">` tag? When using ggplot figures I don't mind mobile users zooming in to read the axis labels.

**Comment by gadenbuie** [comment]
I'm hoping this is resolved for everyone. I've tried the link provided by the OP and it seems to be rendering as expected! Thanks everyone involved in working on this issue. If you have a similar or related problem, please open a new issue.
