### ISSUE TITLE
Vertical margins around plots with "fig_mobile: no"

### ISSUE THREAD

**Issue by twentytitus** [rstudio/flexdashboard#292]
With fig_mobile: no the height of boxes around images gets too large in mobile view, resulting in vertical margins around the plots. Consider this example:

``````
---
title: "Example"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    fig_mobile: no
---

## { .tabset } 

### Chart 1

```{r}
par(bg = 'lightblue')
plot(iris$Sepal.Length, iris$Sepal.Width)
```

### Chart 2

```{r}
par(bg = 'lightgreen')
plot(iris$Petal.Length, iris$Petal.Width)
```
``````

If I open the HTML in a narrow (mobile-sized) browser, empty white vertical margins appear around the plots:

![whitemargin](https://user-images.githubusercontent.com/62478282/100261050-7e6ba000-2f4a-11eb-9d10-d5fc21dc9c96.png)

I suspect the issue is that the size of the containers is still the one that would be needed for the mobile-adapted images.

```
> packageVersion("flexdashboard")
[1] ‘0.5.2’
```

Thanks for this very nice package that makes creating beautiful websites so easy!
Titus

**Comment by cpsievert** [comment]
This is general problem that exists regardless `fig_mobile` and the device's viewport dimensions. The only "fool-proof" way to work around it is to use `renderPlot()`:

````yaml
---
title: "Example"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
---

## { .tabset } 

### Chart 1

```{r}
renderPlot({
  plot(iris$Sepal.Length, iris$Sepal.Width)
}, bg = 'lightgreen')
```

### Chart 2

```{r}
renderPlot({
  plot(iris$Sepal.Length, iris$Sepal.Width)
}, bg = 'lightgreen')
```
````

The problem is that, without `runtime: shiny` R images have to be rendered assuming a certain aspect ratio that may or may not be relevant for the end users device. Unfortunately, there's no real way to address that problem unless you have access to an R runtime so that you can `replayPlot()` with the appropriate dimensions
