### ISSUE TITLE
Icon is not showing in the dashboard

### ISSUE THREAD

**Issue by msgoussi** [rstudio/flexdashboard#296]
I am trying to use specific icon and it is not working at all, i contacted (https://github.com/FortAwesome/Font-Awesome/issues/5301) and they stated "Sorry, we do not provide support for third-party software".
I am wondering how to add local png picture as an icon in the valueBox function 

---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
valueBox(value = 1000,  caption = "Death Cases",  icon = "fas fa-heart-broken", 
           color = "red")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

**Comment by cderv** [comment]
I think it is not working as Flexdashboard will use Fontawesome version 5.1.0 and the icon you want has been existing since 5.6.0 only it seems 

* https://github.com/FortAwesome/Font-Awesome/issues/751

This would require an update.
https://github.com/rstudio/rmarkdown/issues/1661

**Comment by tagliala** [comment]
Hi @cderv thanks.

I confirm, an update is necessary. We also list the version "required" by icons in the docs and `heart-broken` mentions 5.10.2, and it is preferable to refer to docs version (except for some bugs)

In this case, the Pro duo-tone style has been fixed in 5.10.2, so there is no difference between 5.6.0 and 5.10.2, but in other case you may find a different/bugged glyph or icons that won't work at all because they have been made available for free later

Ref: https://fontawesome.com/icons/heart-broken?style=solid

![image](https://user-images.githubusercontent.com/556268/104008454-c7e61680-51a9-11eb-8ad2-501a9bb63a9d.png)

**Comment by msgoussi** [comment]
@cderv is there a way to include png picture as an icon in the valueBox?

**Comment by cpsievert** [comment]
Closing here since the update needs to happen in rmarkdown, not flexdashboard. Please follow rstudio/rmarkdown#1661 for progress

**Comment by msgoussi** [comment]
Hi..
I am a simple user and I have icons from 16px to 256px in png format (other sources such as https://www.flaticon.com/).

How can i use it in valuebox function!!! 
Why we need to depend on Font Awesome or Ionicons or Bootstrap Glyphicons!!!!!
Thanks
