### ISSUE TITLE
runGist or runGithub for flex dashboard

### ISSUE THREAD

**Issue by rbcavanaugh** [rstudio/flexdashboard#302]
Is there anyway to use runGist or runGithub with flex dashboard? I've tried to fuss with gistr and source_gist() from devtools without any luck. These functions all appear to require a ".R" file to send to runApp(). I use the runG...() functions to create desktop shortcuts for shiny apps for less inclined R users, and would like to do the same with flexdashboard. 

Thanks!

**Comment by cpsievert** [comment]
> Is there anyway to use runGist or runGithub with flex dashboard?

I don't believe so; and more generally, I don't think this is possible with any rmarkdown `runtime: shiny` document. At the moment, you'll have the `git clone` the repo you want, then call `rmarkdown::run()` on the document of interest.

Closing this issue since this is really a feature request for rmarkdown, not flexdashboard (please repost here https://github.com/rstudio/rmarkdown/issues/new)
