### ISSUE TITLE
scrolling issue with insertUI and flexdashboard

### ISSUE THREAD

**Issue by MySchizoBuddy** [rstudio/flexdashboard#32]
First How can one paste rmarkdown code inside github. the usual ``` are messing with the r code chucks.

With flexboard 0.2.1 (which adding scrolling of containers) using insertUI to insert a module inside a single chuck doesn't add scrolling to the chunk container.
vertical-flow: scroll is meant to scroll a page when multiple chucks are added to the page.

How can i add scrolling to the chuck itself once it's size is increased?
I have posted working code on [shiny group](https://groups.google.com/forum/#!topic/shiny-discuss/HiwnT57lqJQ).

**Comment by jjallaire** [comment]
What happens if you add the class `.flowing-content-shim` to the chunk's containing section, e.g.

    ### Component Title {.flowing-content-shim}

    ```r
    # Your code here
    ```

**Comment by voxnonecho** [comment]
@jjallaire I'm experiencing a similar issue. Trying to add scroll to a single chunk containing a `rpivotTable` and using `.flowing-content-shim` didn't work.

**Comment by EMIjess** [comment]
I tried adding `{.flowing-content-shim} `with no impact on a flexdashboard when the chunk content output a markdown list that is longer than the vertical page

**Comment by gadenbuie** [comment]
Here's a solution:

1. Create a `div()` with a known id, e.g. `id = "modules"`, with `style="overflow-y: auto; height: 100%"` so that it takes up the full vertical height and scrolls if there's content overflow.

   ```r
   div(id = "modules", style="overflow-y: auto; height: 100%")
   ```

2. Use `insertUI()` to add elements into this container.

3. To have more vertical space for the modules, I'd recommend using `vertical_layout: fill` rather than `scroll`.

Here's the modified version of @MySchizoBuddy's example. (The interesting part is in the last chunk.)

````markdown
---
title: "Insert modules in flexdashboard"
output:
  flexdashboard::flex_dashboard:
    vertical_layout: fill
runtime: shiny
---

```{r}
# include the worldPhones module
worldPhonesUI <- function(id) {
  ns <- NS(id)
  fillCol(height = 400, flex = c(NA, 1),
          inputPanel(
            selectInput(ns("region"), "Region:", choices = colnames(WorldPhones))
          ),
          plotOutput(ns("phonePlot"), height = "100%")
  )
}

# Server function
worldPhones <- function(input, output, session) {
  output$phonePlot <- renderPlot({
    barplot(WorldPhones[,input$region]*1000,
            ylab = "Number of Telephones", xlab = "Year")
  })
}
```

Sidebar {.sidebar}
------------------

Click the insert button below to add worldPhone module to the right. You can add as many modules as you want

```{r}
actionButton("insertModule", "Insert Module")

```

MainPage
-----------------

### World Phones modules

```{r}
div(id = "modules", style="overflow-y: auto; height: 100%")

observeEvent(input$insertModule, {
  id = input$insertModule
  phoneid <- paste0("phones", id)

  callModule(worldPhones, phoneid)
  insertUI(selector = "#modules",
           where = "afterBegin",
           ui = tagList(
             h4(paste0("Module number ", id)),
             worldPhonesUI(phoneid))
  )
})
```
````
