### ISSUE TITLE
DT::datatable() doesn't fill container properly with vertical_layout: scroll

### ISSUE THREAD

**Issue by cpsievert** [rstudio/flexdashboard#321]
This issue only presents itself when used in combination with `data-height` attributes. Note how the table will bleed out of its container here

````
---
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---


Row {data-height=300}
---
  
### Table1 
  
```{r table1}
DT::datatable(mtcars)
```

Row
---
  
### Table2
  
```{r table2}
DT::datatable(mtcars)
```

````

**Comment by stvrd** [comment]
Not sure if this issue is resolved. With DT-0.18, the following simple flexdashboard shows a box too small to properly show the datatable.

With DT-0.13, the box adapts and shows a nice datatable. Therefore, I will continue to work with DT-0.13. Any ideas how to solve this?

```
---
title: "mytitle"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
---
  
```{r}
DT::datatable(mtcars)
```
```
