### ISSUE TITLE
`bslib` stylesheet overrides do not work with `shiny_prerendered` and `rmarkdown` `2.8`

### ISSUE THREAD

**Issue by joemirizio** [rstudio/flexdashboard#343]
## Problem
Referencing stylesheets in the front matter will not override the Bootstrap theme with flexdashboard and `runtime: shiny_prerendered`. This only appears to be an issue in `rmarkdown` `2.8`.

```rmarkdown
---
output:
  flexdashboard::flex_dashboard:
    css:
      - mystyle.css
```

## Background
[`bslib` allows for style overrides](https://rstudio.github.io/bslib/articles/bslib.html#add-rules) by specifying stylesheets in the `css` property in the front matter. This works when rendering `html_document`s (both `shiny` and `shiny_prerendered`). It also works in `flexdashboard` when using `runtime: shiny`, but not with `runtime: shiny_prerendered`.

<details>
<summary>
📸  Expand for visual examples of each
</summary>

### `html_document` + `runtime: shiny`

![Screen Shot 2021-06-08 at 1 58 34 PM](https://user-images.githubusercontent.com/448744/121242891-138d1100-c86b-11eb-90ed-7d8b105b1676.png)

### `html_document` + `runtime: shiny_prerendered`

![Screen Shot 2021-06-08 at 1 58 59 PM](https://user-images.githubusercontent.com/448744/121242958-256eb400-c86b-11eb-9c9d-c342f5c1b255.png)

### `flexdashboard::flex_dashboard` + `runtime: shiny`

![Screen Shot 2021-06-08 at 1 59 19 PM](https://user-images.githubusercontent.com/448744/121243044-446d4600-c86b-11eb-887a-e36338029029.png)

### `flexdashboard::flex_dashboard` + `runtime: shiny_prerendered`

![Screen Shot 2021-06-08 at 1 59 45 PM](https://user-images.githubusercontent.com/448744/121243068-4cc58100-c86b-11eb-9f50-a6b8b4eca318.png)
</details>

It appears that the theme CSS (`cosmo` in this example) is applied _after_ the prerendered HTML is loaded, thus overriding the added rules (`nes`).
![Screen Shot 2021-06-08 at 3 01 23 PM](https://user-images.githubusercontent.com/448744/121242694-dc1e6480-c86a-11eb-943b-56cbaf5f86a6.png)
![Screen Shot 2021-06-08 at 3 00 28 PM](https://user-images.githubusercontent.com/448744/121242708-df195500-c86a-11eb-8f7c-a2cb8c4ebce5.png)

## Steps to reproduce
1. Install `rmarkdown` `2.8` (latest version)
2. Create an RMarkdown document with the following code
```rmarkdown
---
title: "bslib css overrides"
runtime: shiny_prerendered
output:
  flexdashboard::flex_dashboard:
    css:
      - https://unpkg.com/nes.css@latest/css/nes.min.css
---
```{r, context="server"}
print("Hello World")
``` #end
```
2. Note the NES stylesheet changes the cursor, but the default `cosmo` theme overrides the font, for example.

**Comment by cpsievert** [comment]
This happens because, in the non-`{bslib}` usage of `html_document` (i.e., no specified `theme`), `css` files appear before bootstrap (as shown in your screenshot). However, in the `{bslib}` case,  `css` will be included after Bootstrap, so you can workaround the issue like this:

````
---
title: "bslib css overrides"
runtime: shiny_prerendered
output:
  flexdashboard::flex_dashboard:
    theme:
      version: 4
      # Include the font files as well!
      base_font:
        google: Press Start 2P
    css:
      - https://unpkg.com/nes.css@latest/css/nes.min.css
---

```{r, context="server"}
print("Hello World")
```
````

I feel like, in the non-`{bslib}` case, `css` should appear after Bootstrap, but it might be too late to change that (cc @cderv).

**Comment by cderv** [comment]
I just pushed a fix for this I believe. @joemirizio can you try the PR ? 
````r
remotes::install_github("rstudio/flexdashboard#344")
````

@cpsievert even without bslib, the CSS should be inserted after the HTML dependencies, including bootstrap. 
This is an issue here specific to flexdashboard because while fixing something with shiny_prerendered in rmarkdown, we did not made the change to flexdashboard own custom template. A specific placeholder needs to be inserted into the template so that the HTML dependencies are inserted in the correct place. This is because `header-includes` Pandoc's variable is not used with shiny and the HTML dependencies where added at the end of the `<head>` leading to the behavior above. The PR introduce the missing piece which should fix the issue.

**Comment by joemirizio** [comment]
Thanks for looking into this! I tested with the PR version and it worked great
