### ISSUE TITLE
Hosting or Publishing a Flexdashboard .rmd file

### ISSUE THREAD

**Issue by ndsubison2178** [rstudio/flexdashboard#41]
I have a basic test1.rmd file. I am wondering what is the equivalent of 

`runApp(shinyApp(ui, server), host = "0.0.0.0")` 

 in Flexdashboard ? 

When I open this `test1.rmd` app in a browser the default address in the browser is` http://mylocal_ip:8021/test1.rmd`

**Comment by jjallaire** [comment]
It's rmarkdown::run

You can host it on your local workstation (so long as the other folks on
the LAN have access) or you can host it on a Shiny Server or shinyapps.io,
see: http://rmarkdown.rstudio.com/authoring_shiny.html#deployment

**Comment by ndsubison2178** [comment]
@jjallaire  Thanks JJ.

**Comment by datajules** [comment]
> I have a basic test1.rmd file. I am wondering what is the equivalent of
> 
> `runApp(shinyApp(ui, server), host = "0.0.0.0")`
> 
> in Flexdashboard ?
> 
> When I open this `test1.rmd` app in a browser the default address in the browser is`http://mylocal_ip:8021/test1.rmd`

Try to use rmarkdown::run, and add your IP adress and port.

rmarkdown::run("test1.rmd", shiny_args = list(host="0.0.0.0",port=5050))

**Comment by paresh1982** [comment]
I'm not getting where to write this 
rmarkdown::run("test1.rmd", shiny_args = list(host="0.0.0.0",port=5050)) command for it to work.

**Comment by b-rodrigues** [comment]
Hi, same as paresh1982, where should this code go? I put it inside an `app.R` file, but it's not working. Trying to deploy flexdashoabrds on my own shiny server.

**Comment by cderv** [comment]
@b-rodrigues if you are using a shiny server (as in the product), you just have to deploy the Rmd file there and the product will run the `rmarkdown::run()` command for you. See https://docs.rstudio.com/shiny-server/#r-markdown

@paresh1982 the command `rmarkdown::run` is the one to exectute in a R session to have the file served using shiny runtime. You can type it in a R console, put it in a script and execute, or run in terminal using `Rscript -e ...`

**Comment by b-rodrigues** [comment]
Thanks @cderv , however, something's still not working. I have copied the old faithful example to make sure that the issue was not with my particular dashboard. I have my shiny server running on my raspberry pi, and you can access my apps here:

http://shinybrodriguesco.duckdns.org:3838/

as you can see, there are several apps. You can see that golem_demo works, as do both hello world apps. The newspaper app and the old_faithful are both flexdashboards, and neither work. Here's the directory tree on my server:

```
ubuntu@ubuntu:~/shiny-server/apps/old_faithful$ ls
index.Rmd
```

I installed shiny server through docker, following [this tutorial](https://github.com/hvalev/shiny-server-arm-docker), this means that the individual apps are not dockerized, only the shiny server product itself. Could this be the reason? I don't understand why standard shiny apps work and not the flexdashboards. Any further help really appreciated!
