### ISSUE TITLE
Gauge Output not rendering when I publish to shinyapps.io

### ISSUE THREAD

**Issue by jmunene** [rstudio/flexdashboard#94]
This is the code that I am using to render a gauge
`renderGauge({
        select <- reactive({
        input$select})
   call_data_f <- pbrCalls_Data %>%
        filter(pbrCalls_Data$village==select())
sum_table <- round(sum(call_data_f$status_match,na.rm = TRUE)/sum(complete.cases(call_data_f$status_match))*100)
gauge(sum_table, min = 0, max = 100, symbol = '%', gaugeSectors(
    success = c(75, 100), warning = c(40, 74), danger = c(0, 39)
  ))
})`

When I knit locally, the gauge appears correctly as shown below:

![screenshot_092916_012059_pm](https://cloud.githubusercontent.com/assets/13235212/18950150/2c68dc6a-8647-11e6-9d0e-985bf5c2bcb2.jpg)

But after publishing to shinyapps.io, I can only see the 0, the %age and 100, no gauge:

![screenshot_092916_012206_pm](https://cloud.githubusercontent.com/assets/13235212/18950175/546a5d42-8647-11e6-92bd-ebbd6ef8d8d3.jpg)

**Comment by cinkie** [comment]
I ran into the same issue. The display is also the same, only showing the numbers not the graph.

**Comment by tybyers** [comment]
+1. No joy on Chrome or Safari

**Comment by jjallaire** [comment]
I have been able to repro this but am still flummoxed as to why it's happening or how to debug it. Here is the minimal repro which will show a guage locally but will fail to show a guage on shinyapps.io (or RSC):

    ---
    title: "Gauge"
    output: flexdashboard::flex_dashboard
    runtime: shiny
    ---

    ### Gauge

    ```{r}
    library(flexdashboard)
    gauge(20, min = 1, max = 50)
    ```

Note that no JavaScript exceptions seem to be thrown. The gauge just doesn't appear.

It's quite difficult to debug the JavaScript since that which is delay loaded by runtime: shiny doesn't seem to show up in the JS debugger. This version exhibits the same problem but at least lets you get at the JavaScript:

    ---
    title: "Gauge"
    output: flexdashboard::flex_dashboard
    runtime: shiny_prerendered
    ---

    ### Gauge

    ```{r}
    library(flexdashboard)
    gauge(20, min = 1, max = 50)
    ```

Note this uses "shiny_prerendered" so required dev versions of rmarkdown and rsconnect to deploy correctly. Here's a running version which exhibits the problem: https://jjallaire.shinyapps.io/shiny-gauge-prerenered/

@jcheng5 and @jmcphers I've been at this a few hours to no avail. Any help or pointers you can provide is much appreciated!

**Comment by jmcphers** [comment]
It's not due to JavaScript but to paths embedded in the SVG. Try opening up an element inspector and looking at the `<path>` elements in the SVG. The paths that draw the gauge have some filters:

    filter="url(#inner-shadow-htmlwidget-2cd55ceb12a55d65897c)"

These filters aren't loading in the deployed file; if you remove the filter attributes the gauge should render correctly (albeit without the shadows the filters add).

Though I have not run any tests to confirm this, I suspect that the reason these filters are broken is because of the `<base href ... >` used on deployed Shiny content. 

There are various workarounds for this; here's one example: https://gist.github.com/leonderijke/c5cf7c5b2e424c0061d2

**Comment by jjallaire** [comment]
@aronatkins and @trestletech I will workaround this locally in flexdashboard for the time being but we probably need a more general solution for SS, RSC, etc.

**Comment by trestletech** [comment]
Ouch. We have seen this a couple of times over the years and the solution has always been to make the underlying library compatible with a foreign base href. I had looked into it a while back and didn't see any other great alternatives, but we can certainly revisit this if need be.

**Comment by jjallaire** [comment]
The issue should be fixed with this commit: https://github.com/rstudio/flexdashboard/commit/80cfb3214737e9267049290df7c2365787239693

@jmcphers Thanks for the assist here! Could you quickly review my fix?

This version can be installed from GitHub via:

```r
devtools::install_github("rstudio/flexdashboard")
```

**Comment by tybyers** [comment]
@jjallaire et al -- thank you very much!  Looks good: https://tybyers.shinyapps.io/gauge_chart/

**Comment by jmcphers** [comment]
@jjallaire fix looks great!

**Comment by cinkie** [comment]
@jjallaire  Thanks! It works in Chrome and Edge now!

**Comment by jmunene** [comment]
Thanks everyone works for me too

**Comment by pssguy** [comment]
There still seem to be issues with Safari
This is the minimal example above

![gaugesafari](https://cloud.githubusercontent.com/assets/2775918/19697902/10b76864-9aa2-11e6-9286-e23e8f62ac24.png)

**Comment by pssguy** [comment]
Anyone else had/having this problem with Safari and, if so, is there a solution?

**Comment by tybyers** [comment]
@pssguy, I just checked on Safari, and I am not having that problem.  My Safari version is 10.0.0.1. What is yours?

**Comment by pssguy** [comment]
@tybers Thanks for comment  I'm a PC guy   Never used Safari but downloaded a Safari for Windows 5.1.7. which seems to be latest but has copyright  2007-2012?? Guess that could be the explanation
Would you mind checking out my [work in progress]( https://mytinyshinys.shinyapps.io/leinsterDC_3/) on a Mac There is a gauge in bottom left corner cheers

**Comment by tybyers** [comment]
@pssguy nice-looking app.  So the gauges work.  But it's weird -- the first time I click on a page (say, Attack or Set Pieces under Team Statistics), the gauge colors aren't showing. The second time, they do.  I haven't the faintest idea why.

![screen shot 2016-10-31 at 1 21 12 pm](https://cloud.githubusercontent.com/assets/6686686/19868270/f5c33c0c-9f6c-11e6-9c6d-56968c72fdc2.png)

![screen shot 2016-10-31 at 1 22 04 pm](https://cloud.githubusercontent.com/assets/6686686/19868305/16520282-9f6d-11e6-9679-46656483f42e.png)

**Comment by philstraforelli** [comment]
I'm experiencing a similar issue as @tybyers with my application, using `shinydashboard`. There are some situations where the gauge icon disappears, and other times they reappear.
